server:
  port: 12000
spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: baiduTest
          uri: https://www.baidu.com
          predicates:
            - Query=uri, baidu
        - id: qqTest
            uri: https://www.qq.com
            predicates:
              - Query=uri, qq