server:
  port: 7000
#spring:
#  application:
#    name: mall-coupon
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#mall:
#  coupon:
#    test:
#      name: conpontest
#
#mybatis-plus:
#  type-aliases-package: com.example.mall.coupon.entity
#  mapper-locations: classpath:**/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto

