server:
  port: 12000

#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        username: nacos
#        password: nacos
#  application:
#    name: mall-ware
#
#
#mybatis-plus:
#  type-aliases-package: com.example.mall.coupon.entity
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto