server:
  port: 12000

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.50.177.9:3306/mall_wms?socketTimeout=60000&connectTimeout=30000&serverTimezone=UTC
    username: root
    password: rootroot123!
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  application:
    name: mall_ware


mybatis-plus:
  type-aliases-package: com.example.mall.coupon.entity
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto